services:
  monerod:
    image: hundehausen/monero-stressnet:latest
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    restart: unless-stopped
    container_name: monerod
    volumes:
      - bitmonero:/home/monero/.bitmonero
    ports:
      - 28080:28080
      - 28089:28089
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-port=28089"
      - "--testnet"
      - "--enable-dns-blocklist"
      - "--max-connections-per-ip=10"
      - "--add-priority-node=95.217.143.178:28080"
      - "--add-priority-node=45.135.180.21:28080"
      - "--add-priority-node=45.135.180.74:28080"
      - "--add-priority-node=185.130.45.183:28080"
      - "--add-priority-node=95.217.143.100:28080"
      - "--add-priority-node=23.145.40.115:28080"

  tor:
    image: goldy/tor-hidden-service:latest
    container_name: tor
    restart: unless-stopped
    links:
        - monerod
    environment:
        MONEROD_TOR_SERVICE_HOSTS: 28089:monerod:28089
        MONEROD_TOR_SERVICE_VERSION: '3'
    volumes:
        - tor-keys:/var/lib/tor/hidden_service/

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  bitmonero:
  tor-keys:
